# -*- coding: utf-8 -*-
"""YOLOv5_training.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lCv1c4ECMu4loQu_FrWD-ZpFZQQ2ld3
"""

# 구글 드라이브에 연동시켜주는 코드
from google.colab import drive
drive.mount('/content/gdrive')

# 임포트문 모음
import torch
from IPython.display import Image

# Commented out IPython magic to ensure Python compatibility.
# 이 경로로 들어가는것
# %cd /content/gdrive/MyDrive/

# YOLOv5 다운 받아야 하는 코드 (근데 저번에 이미 다운해서 아마 실행하면 다운 받아져있다고 뜰듯)
!git clone https://github.com/ultralytics/yolov5

# 자기 위치 확인하는 명령어
!pwd

# Commented out IPython magic to ensure Python compatibility.
# YOLOv5 파일 안으로 들어가는 코드
# %cd /content/gdrive/MyDrive/yolov5
!pwd

# YOLOv5 실행시킬 때 필요한 라이브러리 다운
!pip install -r requirements.txt

# warning이라고 경고 나오면 그냥 취소 누르기

# 뭔지 모르겠는데 아마 필요할듯?

from tqdm import tqdm
# import IProgress
from ipywidgets import IntProgress

"""이 코드 이하부터 데이터 학습 시작"""

# 학습 시작
!python train.py --img 416 --batch 16 --epochs 100 --data /content/gdrive/MyDrive/yolov5/data/dataset.yaml --weights yolov5s.pt --cache


# 맨 아래에 결과로 Results saved to runs/train/exp9 이렇게 쓰여져있음

# 검사
!python detect.py --weights /content/gdrive/MyDrive/yolov5/runs/train/exp9/weights/best.pt --img 416 --conf 0.25 --source /content/gdrive/MyDrive/yolov5/data/train/1_5person.jpg

# .tflite안드에는 무거운걸 다룰 수 없어서 가볍게 만들어주는 것.
# .pt는 무거운거 .tflite는 가벼운 것

# !!!!!! --weights 뒤에 모델 넣어주기!(경로 잘 보기)
!python export.py --weights /content/gdrive/MyDrive/yolov5/runs/train/exp9/weights/best.pt --include tflite --img 416

# 검사 // 앞에는 검사할 모델 뒤에는 검사할 사진(source)
!python detect.py --weights /content/gdrive/MyDrive/yolov5/runs/train/exp5/weights/best-fp16.tflite --img 416 --conf 0.25 --source /content/gdrive/MyDrive/yolov5/data/train/16_3cat.jpeg

